/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Garage: typeof import('./components/Garage/Garage.vue')['default']
    GarageCarDetailsModal: typeof import('./components/Garage/GarageCarDetailsModal.vue')['default']
    GarageCarRadar: typeof import('./components/Garage/GarageCarRadar.vue')['default']
    GarageCarTitle: typeof import('./components/Garage/GarageCarTitle.vue')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PDialog: typeof import('primevue/dialog')['default']
    POverlayPanel: typeof import('primevue/overlaypanel')['default']
  }
}
