/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CarPerformanceRadar: typeof import('./components/Garage/CarPerformanceRadar.vue')['default']
    Garage: typeof import('./components/Garage/Garage.vue')['default']
    GarageCarTitle: typeof import('./components/Garage/GarageCarTitle.vue')['default']
  }
}
